name: terramind
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - attrs=25.4.0
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - click=8.3.0
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - fiona=1.10.1
  - freexl=2.0.0
  - gdal=3.10.3
  - geos=3.14.0
  - geotiff=1.7.4
  - giflib=5.2.2
  - hdf5=1.14.6
  - icu=75.1
  - json-c=0.18
  - krb5=1.21.3
  - lerc=4.0.0
  - libaec=1.1.4
  - libarchive=3.8.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=21.1.2
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgdal-core=3.10.3
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - librttopo=1.1.0
  - libspatialindex=2.1.0
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxml2-devel=2.15.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - lz4-c=1.10.0
  - lzo=2.10
  - minizip=4.0.10
  - ncurses=6.5
  - openssl=3.5.4
  - pcre2=10.46
  - pip=25.2
  - proj=9.7.0
  - pyparsing=3.2.5
  - python=3.11.13
  - python_abi=3.11
  - rasterio=1.4.3
  - readline=8.2
  - rtree=1.4.1
  - setuptools=80.9.0
  - shapely=2.1.2
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.50.4
  - tk=8.6.13
  - uriparser=0.9.8
  - wheel=0.45.1
  - xerces-c=3.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aenum==3.1.16
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - albucore==0.0.16
      - albumentations==1.4.10
      - alembic==1.17.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - authlib==1.6.5
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==6.2.1
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cryptography==45.0.7
      - cycler==0.12.1
      - cyclopts==3.24.0
      - databricks-sdk==0.68.0
      - diffusers==0.30.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.119.0
      - fastmcp==2.12.4
      - filelock==3.20.0
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gdown==5.2.0
      - geopandas==1.1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - h11==0.16.0
      - h5netcdf==1.6.4
      - h5py==3.15.0
      - hdf5plugin==6.0.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonargparse==4.35.0
      - jsonnet==0.21.0
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lazy-object-proxy==1.12.0
      - lightly==1.5.22
      - lightly-utils==0.0.2
      - lightning==2.5.1.post0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mcp==1.17.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mlflow==3.4.0
      - mlflow-skinny==3.4.0
      - mlflow-tracing==3.4.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - munch==4.0.0
      - networkx==3.5
      - numba==0.62.1
      - numpy==1.26.4
      - omegaconf==2.3.0
      - onnx==1.14.1
      - onnxconverter-common==1.16.0
      - onnxmltools==1.13.0
      - onnxruntime==1.22.0
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - packaging==24.2
      - pandas==2.3.3
      - parse==1.20.2
      - pathable==0.4.4
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - pretrainedmodels==0.7.4
      - propcache==0.4.1
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.10
      - pycparser==2.23
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pydantic-settings==2.11.0
      - pygments==2.19.2
      - pyogrio==0.11.1
      - pyperclip==1.11.0
      - pyproj==3.7.2
      - pysocks==1.7.1
      - pytest==8.4.2
      - pytest-sugar==1.1.1
      - python-box==7.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rich==13.9.4
      - rich-rst==1.3.2
      - rioxarray==0.19.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - segmentation-models-pytorch==0.4.0
      - sentry-sdk==2.41.0
      - six==1.17.0
      - skl2onnx==1.19.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - starlette==0.48.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - terratorch==1.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.4
      - timm==1.0.20
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchgeo==0.7.0
      - torchmetrics==1.8.2
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - typeshed-client==2.8.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - wandb==0.22.2
      - werkzeug==3.1.1
      - xarray==2025.10.1
      - xgboost==1.7.6
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /opt/miniconda3/envs/terramind
